package com.example.fitness.database

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a user entity in the database.
 * This class is annotated with @Entity to define the database table structure.
 *
 * @property id The unique primary key for the user, auto-generated by the database.
 * @property email The email address of the user, used as a unique identifier for authentication.
 * @property password The user's password, stored securely (should be encrypted).
 */
@Entity(tableName = "users")
data class User(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0, // Unique identifier for each user record
    val email: String, // User's email address
    val password: String, // User's password (should be encrypted)
    val name: String? = null, // User's full name
    val age: Int? = null, // User's age
    val height: Float? = null, // User's height in meters
    val weight: Float? = null, // User's weight in kilograms
    val goal: String? = null, // User's fitness goal ("gain muscle" or "lose weight")
    val bmi: Float? = null // Calculated Body Mass Index
)

